### ISSUE TITLE
"Search all discussion for" button disappears

### ISSUE THREAD

**Issue by rafaucau** [flarum/framework#3400]
## Bug Report

**Current Behavior**
When I try to search for something, this button disappears for a while (It comes back when the suggestions are loaded). When I press enter key, what I have typed disappears instead of going to the results. This is a bad experience for users, especially when the forum has a lot of discussion and the search engine is slow.

**Steps to Reproduce**
1. Type something in the search field
2. Press enter key

**Expected Behavior**
Pressing enter should go to the search results instead of erasing what user typed.

**Screenshots**

https://user-images.githubusercontent.com/25438601/163574346-b7a4dc89-5d26-4ce5-94e0-4e2d25f70c39.mp4

**Environment**
- Flarum version: 1.2.1

**Comment by tankerkiller125** [comment]
What version of Chrome is this happening in? I'm unable to replicate in MS Edge and I don't have Chrome installed.

Edit: Unable to get it to replicate on a VM with Chrome fresh installed.

**Comment by matteocontrini** [comment]
I can reproduce the issue on Firefox. Set the browser network throttling to a low speed to make it easier to see the issue.

**Comment by rafaucau** [comment]
This occurs on every browser. If your forum's search is fast and you have fast internet, this is hard to catch.
Try it here: https://forum.android.com.pl/ - the search is slow, so it will be easier to catch

**Comment by SychO9** [comment]
Happens a lot to me, pretty annoying.
