### ISSUE TITLE
A problem about password hasher

### ISSUE THREAD

**Issue by ExerciseBook** [flarum/framework#3406]
I noticed that Bcrypt is hardcoded in install page.
https://github.com/flarum/framework/blob/379c06332a0789b892b0426b3eb8be24bd557db4/framework/core/src/Install/AdminUser.php#L40

But after installing, password hasher was selected by Laravel configuration.
https://github.com/flarum/framework/blob/379c06332a0789b892b0426b3eb8be24bd557db4/framework/core/src/Foundation/Application.php#L351

Is that by designed or mistake?

**Comment by askvortsov1** [comment]
Before Flarum is installed, there is no `config.php` file or database settings table, so there's no way to specify which hasher should be used at the moment.

I don't see us adding this to the form; however, I think we would be open to a PR that adds support for selecting a different Laravel-supported hasher if installing through the CLI. That being said, I don't think the Flarum core team intends to develop this ourselves, so I'm going to close this issue for now.
