### ISSUE TITLE
The title of the navigation bar is disappear

### ISSUE THREAD

**Issue by datlechin** [flarum/framework#3415]
## Bug Report

**Current Behavior**
The title on the mobile trend bar is missing when the url contains a query string that is not valid for Flarum

**Steps to Reproduce**
1. Add some query string that not part of Flarum's query strings ( like ?source=, ?utm=, ...)
2. The title will be disappear (only on mobile)

**Screenshots**
![Screenshot_20220507-013723_Chrome](https://user-images.githubusercontent.com/56961917/167198637-e4d777be-4d9d-4951-8638-58850e622b76.png)

**Comment by dsevillamartin** [comment]
The matching behavior on desktop is that none of the sidebar links are marked as "active". The missing title here means that there's no active sidebar item.

One way to solve this would be ignoring query parameters. Not sure if that'd cause issues with other exts.

**Comment by SychO9** [comment]
Can no longer reproduce.
