### ISSUE TITLE
Default settings values are not returned

### ISSUE THREAD

**Issue by imorland** [flarum/framework#3438]
## Bug Report

**Current Behavior**
When calling `$settings->get('some-key-that-is-not-already-in-the-database')`, having already defined a default value in an extensions' `extend.php`, the value returned is `null`

**Steps to Reproduce**
- In `extend.php`
```php
new (Extend\Settings())
  ->default('some-key-that-is-not-already-in-the-database', 'my-default-value'),
  ```
  - Call that settings key
  ```php
 $settings->get('some-key-that-is-not-already-in-the-database')
  ```
  - Notice the value is `null`

**Expected Behavior**
The default value as defined in `extend.php` should be returned.

**Environment**
- Flarum version: 1.3
- Website URL: local
- Webserver: n/a
- Hosting environment: n/a
- PHP version: 8.0.13
- Browser: n/a

**Additional Context**

**Comment by davwheat** [comment]
I noticed this too but assumed it was an issue with my local setup.

**Comment by SychO9** [comment]
I can reproduce this, which I find very confusing as the test still succeeds, I also remember testing this extender very well 🤔

allow me to investigate this. 

https://github.com/flarum/framework/blob/584884a3c949bdb7f59c5985603291347c7aa793/framework/core/tests/integration/extenders/SettingsTest.php#L170-L184
