### ISSUE TITLE
[Suspend] Suspension info modal shown even if user is not suspended anymore

### ISSUE THREAD

**Issue by matteocontrini** [flarum/framework#3441]
## Bug Report

**Current Behavior**

The suspension info modal is shown to users even if the suspension isn't in effect anymore.

**Steps to Reproduce**
1. Suspend a user
2. Wait for the suspension time to pass
3. Login as the user and notice the suspension info modal
4. Optionally, dismiss the modal, clear cookies/local storage, login again and see the suspension modal another time. Repeat forever...

**Expected Behavior**

The modal shouldn't be shown to users if `suspend_until` is in the past.

**Environment**
- Flarum version: 1.2.1

(the rest is not relevant...)

**Comment by SychO9** [comment]
confirmed
