### ISSUE TITLE
Reply notifications not being sent out to users

### ISSUE THREAD

**Issue by SychO9** [flarum/framework#3443]
## Bug Report

**Current Behavior**
When someone replies to a discussion you follow, you do not receive a notification.

**Steps to Reproduce**
1. Follow a discussion you have read.
2. Reply with a different user
3. No notification is sent out.

**Expected Behavior**
A notification should be sent out.

**Environment**
- Flarum version: Introduced in 1.3.0

**Possible Solution**
**Context:** If the actor has read the post number 6 which at the time was the last, and someone replies, the _subscriptions_ extension sends out notifications to those following who have last read post number 6. It doesn't send notifications to all those who have last read less than post number 7 (newest reply) to avoid repetitive notifications.

**Additional Context**
It does this by listening to the `Posted` event and using the `$event->post->discussion->last_post_number` (should be 6), it expects to run before `DiscussionMetadataUpdater` subscriber (updates `last_post_number` to 7), however in 1.3 this PR (https://github.com/flarum/framework/pull/3373) changes the behavior and leads to extension listeners to run after all core listeners. So what's happening now is that the `last_post_number` used in the subscriptions listener has already been updated to 7 in this example.

**v1.2** | **v1.3**
-- | --
![Screenshot from 2022-05-31 14-23-56](https://user-images.githubusercontent.com/20267363/171190829-bef5f349-e929-4689-919a-071cbfe6818b.png) | ![Screenshot from 2022-05-31 14-22-04](https://user-images.githubusercontent.com/20267363/171190845-041c8165-29cd-4510-9275-42f02c197ea5.png)

**Potential Solutions**
* We could introduce a listener priority system to make sure the listener runs before the discussion metadata updater listener.
* We could go for a `last_post_number - 1` change in the subscriptions listener. This wouldn't be a solution if we were still using `post_number_index`, but since we now count new post numbers based on previous existing post number, it might be fine to do.

**Comment by luceos** [comment]
As the post has already been saved when the listener is dispatched, why don't we use `$post->number -1` instead? Relying on a relationship inside that listener seems unnecessary and the number should already have been updated.

**Comment by SychO9** [comment]
Yes I believe we could just do that, I would just like to make sure that is the case first, I'll investigate further sometime later today.

**Comment by matteocontrini** [comment]
Is there a chance for this fix to be released as a patch? I would personally skip 1.3.0 altogether otherwise...

**Comment by luceos** [comment]
@matteocontrini yes we'll do a patch release for this soon.
