### ISSUE TITLE
The tag prompt shows up even for a `0 to 0` tag requirements

### ISSUE THREAD

**Issue by ornanovitch** [flarum/framework#3444]
## Bug Report

Discovered on Nightly by working around here: https://discuss.flarum.org/d/30939-eliminate-choose-tags-for-your-discussion-screen

**Current Behavior**
If you require 0 tag (0 to 0 for both primary & secondary), the user can post without any tag but will see the tag prompt and will have to confirm without having the possibility to select anything.

**Steps to Reproduce**
1. As admin, set both tag requirements from 0 to 0 for both tag requirements
2. As a user, create a new discussion and publish it
3. You have to see and validate the tag prompt for nothing

**Expected Behavior**
If tag requirements are from 0 to 0, I should be able to publish without having to see the tag prompt.

**Screenshots**
![Screenshot 2022-06-01 at 22-52-33 Flarum_nightly](https://user-images.githubusercontent.com/34077099/171499460-3ce70465-be6b-40b9-9a1b-5c390b18fbb4.png)

**Environment**
Nightly

**Possible Solution**
I think there should be a new scenario here:

`tag requirements === 0` : no prompt at all (except for admins if tags do exist)

**Comment by SychO9** [comment]
I think it is intended behavior for the most part.

The only thing that can be counted as a bug is if the user cannot choose any tags (requirement === 0) the modal should not be shown (should be relatively easy to change).

But any other suggested change is not really addressing a bug so would be more appropriate in the [proposals tag on discuss](https://discuss.flarum.org/t/proposals).

**Comment by clarkwinkelmann** [comment]
This is the relevant code

https://github.com/flarum/framework/blob/29362ed92481cb7152769f44643f47f8a8d530b7/extensions/tags/js/src/forum/addTagComposer.js#L65-L68

Right now it seems like the modal will always open if no tags have been selected, unless there are zero tags the user has access to, in which case it wouldn't open.

**Comment by ornanovitch** [comment]
> unless there are zero tags the user has access to, in which case it wouldn't open

 :thinking:  that's it, so this "unless there are zero tags the user has access to" should be extended to the case where tag requirements rule are set `from 0 to 0` right?

@SychO9 I hear you, but I thought it worth nothing to give my two cents about a general solution which could give a more consistent behavior at the same occasion.

In any case, it feels important to me to notice that "Choose Tags for Your Discussion" without something like a "No Thanks" button when tags are optional sounds like a counter intuitive design which could be solved somehow - and thus is neither a bug, nor a simple enhancement proposal.

**Comment by SychO9** [comment]
> :thinking: that's it, so this "unless there are zero tags the user has access to" should be extended to the case where tag requirements rule are set from 0 to 0 right?

Yup, it should take into consideration that as well.

@Ornanovitch I'm not disagreeing with what you are proposing in terms of the other scenarios by the way, and I can definitely understand what you mean. We're just trying to keep the number of issues down to reproducible bugs only, hence why we're encouraging people to direct any non-bug issues to discuss 👍🏼 at the moment.

**Comment by clarkwinkelmann** [comment]
Based on the code, it seems like the `!chosenTags.length` check is there explicitly to open the modal even if the conditions for zero minimum tags were met.

Combined with the other check for the number of tags the user can use, I would assume this was done by design. Essentially "if the user can select tags but didn't select any, show them the modal to make sure they didn't forget to select any".

Based on this, I would say the current implementation is an intended feature. So maybe this would be better solved by introducing a new setting that specifically controls whether the user should be prompted when they forget to select any tag.

Based on your use case you described on the forum, if you expect users to never select tags, you could actually change all tags to be read-only, in which case the number of available tags would become zero and the modal wouldn't open.

**Comment by ornanovitch** [comment]
I'm not sure I follow you completely:

> open the modal even if the conditions for zero minimum tags were met

The bug here is that the modal show up even if the conditions for zero minimum tags _and zero maximum tags_ were met. It feels like this possibility hasn't been anticipated within this design.

> I would assume this was done by design. Essentially "if the user can select tags but didn't select any, show them the modal to make sure they didn't forget to select any"

Precisely: if the user *can* it's totally legit, but if the user can't it's not: it shows a useless empty modal with a unique way out: click ok (see my screenshot)

(this is not my used case on the forum, I was just trying to help someone else when I found this bug^^)

**Comment by davwheat** [comment]
If the tag modal shows up when set to 0 to 0 for both primary and secondary, then this is indeed a bug.

**Comment by ornanovitch** [comment]
I edited my description & title to avoid confusion (I guess that was the source of the misunderstood with Clark).

I added a needed exception for the potential fix: admin should still be prompted for tags if tags do exist, because he/she has the right to bypass tag requirements :)

**Comment by clarkwinkelmann** [comment]
Oh, right! I missed the part about the maximum number being also set to 0. In that case it would indeed make sense to not show the modal since there's no way to make any valid selection anyway.

**Comment by orschiro** [comment]
> Oh, right! I missed the part about the maximum number being also set to 0. In that case it would indeed make sense to not show the modal since there's no way to make any valid selection anyway.

From a user perspective, this would be great! Would also allow admins/mods to assign tags to existing conversations without having users to choose tags (or bypass with that dialog) when submitting a new conversation.
