### ISSUE TITLE
Remove usage of inline CSS

### ISSUE THREAD

**Issue by flawedworld** [flarum/framework#3460]
This would allow for the usage of CSP without needing to use "unsafe-inline".

**Comment by davwheat** [comment]
TextFormatter is FILLED with inline CSS, I believe, which is the main limitation from CSP.

**Comment by SychO9** [comment]
Yup, will be tackled as part of the [roadmap](https://discuss.flarum.org/d/29931-the-future-of-flarum-a-roadmap) once we have a clear action plan for CSP as it gets complicated with the textformatter library and also extensions.

**Comment by JoshyPHP** [comment]
@davwheat Did you mean JavaScript? There's almost no CSS in the library.

**Comment by davwheat** [comment]
ummm yes I did 🙈

**Comment by JoshyPHP** [comment]
Is there a GitHub issue or a thread that tracks discussions/progress on CSP?

**Comment by SychO9** [comment]
There was https://github.com/flarum/issue-archive/issues/125, but there were discussions about the subject on discuss and discord as well I believe.
