### ISSUE TITLE
Test with PHP 8.2

### ISSUE THREAD

**Issue by SychO9** [flarum/framework#3462]
Need to:
- [x] move workflow definitions from `.github` to the monorepo (here) (https://github.com/flarum/framework/pull/3490).
- [ ] start testing with PHP 8.2

**Comment by flawedworld** [comment]
Composer seems to be throwing a strop when using a nightly build of PHP 8.2, so need to figure a workaround out for that.

**Comment by SychO9** [comment]
I see, it might be easier to do the move of workflows first and then test with PHP 8.2,

Thanks for taking this on!
