### ISSUE TITLE
if a tag name is renamed redirect old tag URL to new : flarum/tags

### ISSUE THREAD

**Issue by Hari-Bonda** [flarum/framework#3497]
if a tag name is renamed redirect the old tag slug to new: flarum/tags

example
old - https://discuss.flarum.org/t/test-post
new - https://discuss.flarum.org/t/sandbox

**Comment by SychO9** [comment]
This is a feature request, so please open a discussion about it on the forum's [proposals](https://discuss.flarum.org/t/proposals) tag.

Thanks!
