### ISSUE TITLE
Allow the user to specify a unix socket to connect to a database

### ISSUE THREAD

**Issue by flawedworld** [flarum/framework#3498]
GrapheneOS is currently using ```'unix_socket' => '/run/mysqld/mysqld.sock'``` in production and it works fine, just that the config file needs to manually edited and the database wizard doesn't seem to expose this.

**Comment by SychO9** [comment]
I don't think we'd want more advanced fields on the wizard UI, I think being able to already specify the value through `config.php` is enough?

Closing for now, feel free to discuss further if necessary.

**Comment by askvortsov1** [comment]
I feel like the best course of action here is documenting the `config.php` support in https://docs.flarum.org/config, and possibly somewhere else? Agree that keeping the installation GUI minimal is probably best.

**Comment by SychO9** [comment]
Docs PR opened: https://github.com/flarum/docs/pull/458
