### ISSUE TITLE
Styling issues on Android Chrome 

### ISSUE THREAD

**Issue by orschiro** [flarum/framework#3499]
Apologies if this is not the correct repo to report at. I encountered the below styling issues on the latest version of Chrome Android.

1. Long titles don't show entirely in the notifications area.
2. The margins of the tags don't seem to be correct.

Attaching Screenshots. Taken at community.sheetgo.com.

![Screenshot_20220627-191835_Chrome](https://user-images.githubusercontent.com/170947/176006706-1668e605-3c1e-43b5-bbb9-a0f01c8a6db9.jpg)

![Screenshot_20220627-191724_Chrome](https://user-images.githubusercontent.com/170947/176006764-e5ade6a5-d4ea-4e1d-8612-5588ca841353.jpg)

**Comment by dsevillamartin** [comment]
I can reproduce the first issue on Discuss.
However, I cannot reproduce the second one (the tags list). This may be caused by one of your extensions. or perhaps custom CSS.

**Comment by davwheat** [comment]
I believe the first one is by design. I would however say it should be clear that it is truncated, perhaps with some ellipses?

**Comment by orschiro** [comment]
>  I would however say it should be clear that it is truncated, perhaps with some ellipses?

This would be great!

**Comment by orschiro** [comment]
> I can reproduce the first issue on Discuss.
However, I cannot reproduce the second one (the tags list). This may be caused by one of your extensions. or perhaps custom CSS.

Thanks, let me dig into this one a bit deeper!

**Comment by dsevillamartin** [comment]
The notification header issue is a duplicate of #3408.

I'll close this as there's also not enough information for the second issue. If you find more, please create a new issue and follow the template to provide the requested data. Thank you.
