### ISSUE TITLE
Add backend tests to bundled extensions

### ISSUE THREAD

**Issue by askvortsov1** [flarum/framework#3508]
- [x] Start adding integration tests to bundled extensions
  - [x] flarum/tags (https://github.com/flarum/framework/commit/712286151fdb3be8cf3d189e00f7b501dc97cf51)
  - [x] flarum/subscriptions (https://github.com/flarum/framework/pull/3445)
  - [x] flarum/mentions (https://github.com/flarum/mentions/pull/66)
  - [x] flarum/flags (https://github.com/flarum/framework/commit/be59e77a010e1da8e1ef90f0fe1047ae0e3c6f6a)
  - [x] flarum/approval (https://github.com/flarum/framework/pull/3510)
  - [x] flarum/sticky (https://github.com/flarum/framework/pull/3507)
  - [x] flarum/suspend (https://github.com/flarum/framework/pull/3511)
  - [x] flarum/likes (https://github.com/flarum/framework/pull/3512)
 
I'll use the update feature of the extension generator for this, then fill in some basic tests.

**Comment by SychO9** [comment]
Completed 🫡
