### ISSUE TITLE
& in forum name rendered as &amp; in browser tab

### ISSUE THREAD

**Issue by orschiro** [flarum/framework#3514]
## Bug Report

& in the forum name is not displayed correctly. 

Example at https://www.philundrob.de/ 

The forum title in the browser tab should read Phil & Rob. 

![Screenshot_20220710-121146_Chrome](https://user-images.githubusercontent.com/170947/178140603-4008d967-61f3-4683-a992-646ecf81c74a.jpg)

![Screenshot_20220710-121135_Chrome](https://user-images.githubusercontent.com/170947/178140611-abe77864-cf5b-4485-bd90-d68899ca9d09.jpg)

**Comment by davwheat** [comment]
Can reproduce

![](https://user-images.githubusercontent.com/7406822/179481632-71ad5bcd-c47a-47e8-ad02-119e851817e6.png)
