### ISSUE TITLE
[A11Y] Convert empty links to button elements

### ISSUE THREAD

**Issue by davwheat** [flarum/framework#3519]
![image](https://user-images.githubusercontent.com/7406822/129197274-86305950-e5ae-4d02-bddf-f11df8b71c06.png)

**Comment by Tjs002** [comment]
@davwheat is this issue still open, can i work on this?

**Comment by davwheat** [comment]
Go for it!

**Comment by Tjs002** [comment]
@davwheat can you tell me how to setup the codebase as i am new to opensource

**Comment by SychO9** [comment]
@Tjs002 checkout the docs https://docs.flarum.org/contributing#development-setup
