### ISSUE TITLE
Deleting last posts can cause the discussion to remain read

### ISSUE THREAD

**Issue by SychO9** [flarum/framework#3524]
## Bug Report

**Current Behavior**
If user A has read all of discussion B, and the last posts of that discussion are deleted. The discussion will remain marked as read for a while for user A even with new posts.

**Steps to Reproduce**
1. Create a discussion with many posts as an admin.
2. Read the discussion as user A.
3. Delete last 2 posts as an admin.
4. Create a new post as an admin.
5. Notice discussion still marked as read as user A.

**Expected Behavior**
Discussion should be marked as unread.

**Environment**
- Flarum version: 1.3

**Possible Solution**
What needs to be done is to update the discussion_user table on post deletion, so that last_read_post_number of the discussion for any user where that value was equal to the deleted post number is lowered. And we should add an integration test for this as well.

**Additional Context**
[Add any other context about the problem here.](https://discuss.flarum.org/d/31144-possibly-a-bug)

**Comment by SychO9** [comment]
> What needs to be done is to update the discussion_user table on post deletion, so that last_read_post_number of the discussion for any user where that value was equal to the deleted post number is lowered. And we should add an integration test for this as well.

I think updating the `discussion_user` table on every last post(s) deletion could be bad for very busy/large communities as that's a table with most likely the most rows in the database. @luceos thoughts?

**Comment by luceos** [comment]
@BartVB are you able to pitch in on this one?

**Comment by BartVB** [comment]
Sure.

Updating `discussion_user` is the proper way to do this. Impact on large forums should be fairly limited because there is an index on `discussion_id`. In most cases there is only a couple thousand of rows affected and these rows are very fast to change, all fields in the table are fixed length.

**Comment by luceos** [comment]
So this means the implementation can actually be fairly simple and could even be included in the DiscussionMetaUpdater or whatever that class is called 🙈
