### ISSUE TITLE
Show more (or different) emojis when typing :

### ISSUE THREAD

**Issue by orschiro** [flarum/framework#3527]
Hi all, 

This is concerning the emoji extension. 

When you type : , the extension opens a drop down menu that currently only shows the following emojis. 

![image](https://user-images.githubusercontent.com/170947/178817303-5c27ba53-a3b7-4b00-bbb5-e2fccda91b74.png)

This is confusing as one might think there are no more emojis than that. 

It's not intuitive that the user has to keep on typing to find his emoji. 

Can this drop down list be expanded to show more emojis, or maybe more meaningful ones?

Maybe the most popular ones such as smiley up, down, etc?

Thanks for your attention!

**Comment by SychO9** [comment]
Hey @orschiro, thanks for bringing this up. As it's not a bug and more of a behavior change/feature could you please open it up as a [proposal on discuss](https://discuss.flarum.org/t/proposals) instead?

**Comment by orschiro** [comment]
@SychO9 done, thanks for your quick feedback! :)

https://discuss.flarum.org/d/31202-show-more-or-different-emojis-when-typing
