### ISSUE TITLE
When entering to someone’s profile page inside of a discussion and go back will cause to Stuck

### ISSUE THREAD

**Issue by alligatorrrr** [flarum/framework#3539]
### Current Behavior

[mobile]When entering to someone’s profile page inside of a discussion and go back (slide to right) will cause to a long stuck

### Steps to Reproduce

1. Open a discussion
2. Click one of users’ avatars inside of this discussion
3. Sliding to right [Gesture of Phone] to go back to last page

### Expected Behavior

No stuck

### Environment

- Flarum version: 1.3.1

- Browser: Safari / Chrome

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Comment by luceos** [comment]
Cannot reproduce with 1.4.0 on discuss. Please explain what is "stuck" or provide steps to reproduce that is confirmable.
