### ISSUE TITLE
JS Sourcemaps broken

### ISSUE THREAD

**Issue by SychO9** [flarum/framework#3554]
We need to look into why they no longer point to the correct source files/lines.

**Comment by SychO9** [comment]
This seems to be fine now 🤔

**Comment by davwheat** [comment]
There's still issues with it for me.

Look at Discuss, find fof/geoip. The external parts aren't named correctly. I'm not sure if there are still other issues, though.

**Comment by SychO9** [comment]
Ah yeah, weird.

**Comment by SychO9** [comment]
Let's close this for now as I can't reproduce any issues at the moment so it might have been a fluke.
