### ISSUE TITLE
Improve the internal routing system in some cases.

### ISSUE THREAD

**Issue by iamdarkle** [flarum/framework#3602]
### Current Behavior

There are certain situations where the internal routing system does not seem to display the back button. I think it would be great to use this topic to comment on other cases you have experienced.

### Steps to Reproduce

- When entering profiles from the discussion list
- When accessing a tag

In the case of extensions, I'm not sure if it's a core extensibility issue or a problem with the extensions themselves?
Just to mention a few:
- fof/byobu:
- flarum/subscriptions

### Expected Behavior

Show the back button of the internal routing system, as it seems to work correctly underneath.

### Screenshots

![uArP78t3sW](https://user-images.githubusercontent.com/15818451/184628245-39f72575-7b08-44cc-8f08-7cf8ab294703.gif)

### Environment

- Flarum version: 1.4.1
- Website URL: https://discuss.flarum.org/

**Comment by SychO9** [comment]
This makes sense, though it's not exactly a bug, but a lack of a feature. Right now each page has to push its URL to the history stack, so we can't fix this universally.

I'd like for us to visit this when we tackle the refactor for frontend pages in 2.0.

Let's close this for now, thanks for reporting though!
