### ISSUE TITLE
Readme file for Statistics extension?

### ISSUE THREAD

**Issue by orschiro** [flarum/framework#3604]
### Current Behavior

Hi all, 

Could https://github.com/flarum/statistics add a readme file that explains the basics of this extension?

For example what the green and grey line mean and what the difference between the two is.

That's not really clear from just looking at it (at least for me).

Thanks!

### Steps to Reproduce

1. Install the extension
2. No readme file present

### Expected Behavior

There should be a readme file that explains the basics.

### Screenshots

![image](https://user-images.githubusercontent.com/170947/184894507-1393f808-fba9-47ad-bde1-dad6ed9d8add.png)

![image](https://user-images.githubusercontent.com/170947/184894711-a2c65777-2171-4937-9154-5c7979299dfb.png)

### Environment

- Flarum version: 1.4.0

**Comment by SychO9** [comment]
This isn't a bug though 😅 

I honestly don't know what the gray line means either. The extension needs a refactor/rewrite imo.

**Comment by davwheat** [comment]
Grey line is the last period -- same data as is used for the % comparisons

**Comment by orschiro** [comment]
Thanks David.

So for example, if I select last 7 days, then green is last 7 days and grey
the 7 days before that?

**Comment by davwheat** [comment]
Yep, spot on!

**Comment by orschiro** [comment]
Thanks! Maybe a legend somewhere next to the graph would help explain that?

**Comment by SychO9** [comment]
@orschiro are the changes in the [linked PR](https://github.com/flarum/framework/pull/3654) better? (screenshots)

**Comment by orschiro** [comment]
@SychO9 yes, much better, thank you so much!
