### ISSUE TITLE
Tooltip does not work on a disabled button

### ISSUE THREAD

**Issue by SychO9** [flarum/framework#3613]
### Current Behavior

When using the tooltip component on a disabled button the tooltip isn't visible on hover.

### Steps to Reproduce

```jsx
<Tooltip text="hello!">
  <Button class="Button" disabled={true}>Hi!</Button>
</Tooltip>
```

### Expected Behavior

Tooltip should show up.

### Environment

- Flarum version: 1.5.0-dev
- Browser: Chrome 104

**Comment by davwheat** [comment]
This is a limitation of Bootstrap Tooltips -- the element has to be wrapped in another element.

See: https://getbootstrap.com/docs/3.4/javascript/#callout-tooltip-disabled

**Comment by SychO9** [comment]
Oh wow, well then. That'll be fixed once we unbootstrap I guess (*at least I remember that being potentially the plan in the long run*)
