### ISSUE TITLE
Unread is not visible in navigation sidebar

### ISSUE THREAD

**Issue by Eldenroot** [flarum/framework#3642]
### Current Behavior

Unread text is not fully visible. Tested on Chrome and Edge

![image](https://user-images.githubusercontent.com/778890/190636238-ead74669-68ae-47c0-b4e0-d88755728a27.png)

### Steps to Reproduce

Go to some discussion with a lot of posts...

### Expected Behavior

The unread text should be fully visible 

### Screenshots

![image](https://user-images.githubusercontent.com/778890/190636287-8e2737f3-ba91-4572-8de1-9122fe83dff8.png)

### Environment

- Flarum version: 1.5.0 (flarum.org board)
- Website URL: https://discuss.flarum.org/
- Webserver: [e.g. apache, nginx]
- Hosting environment: [e.g. shared, vps]
- PHP version: x.y.z
- Browser: [e.g. chrome 67, safari 11]

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Comment by luceos** [comment]
This has been the behavior since the earliest beta's. If we want to change this we need to Approve it first. Please use https://discuss.flarum.org/t/proposals to file it for consideration.

**Comment by matteocontrini** [comment]
Is a proposal and a discussion needed to decide whether it's ok to have cut text in the UI? 🤔 I don't see how this could not be considered a bug.

**Comment by davwheat** [comment]
I also agree.

If we have a bug that has existed since early betas, that doesn't mean we should class it as expected behaviour now we're in stable.

What's your opinion @luceos?

**Comment by Eldenroot** [comment]
> This has been the behavior since the earliest beta's. If we want to change this we need to Approve it first. Please use https://discuss.flarum.org/t/proposals to file it for consideration.

This is funny :) Lets talk about a bug and make a poll if we can consider it as a bug :D

**Comment by luceos** [comment]
I am trying to follow the procedure as laid out [here](https://discuss.flarum.org/d/30827-updating-our-issue-creation-protocol). I can see that in this situation I have been too inconsiderate.

**Comment by Eldenroot** [comment]
Did you follow EU politics with this protocol? :D Why make things easy if there is a long and complicated shortcut :) Nevermind, it is up to you... I did my job, now it is your turn... do your work, keep Flarum alive :)

**Comment by SychO9** [comment]
@luceos has reopened the issue, there is no need for any unnecessary comments. Thank you.
