### ISSUE TITLE
Admin dashboard on iPhone problems

### ISSUE THREAD

**Issue by justoverclockl** [flarum/framework#3649]
### Current Behavior

Permission grid on mobile (iOS) is almost unusable 

### Steps to Reproduce

On mobile

1- go to admin dashboard
2- go to the permissions tab
3- try to set new permissions 

### Expected Behavior

Ui-ux need some fixes to work well on mobile

### Screenshots

https://streamable.com/lwclx3

### Environment

- Flarum version: 1.5.0
- Website URL: http://Flarum.it
- Webserver: under Flarum foundation 
- Hosting environment: under Flarum foundation
- PHP version: 8
- Browser: safari iOS 16

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Comment by umutcandev** [comment]
On the mobile side, the situation is the same on the Android side. I hope it will be resolved as soon as possible.
