### ISSUE TITLE
[testing] Formatter cache is not cleared after tests

### ISSUE THREAD

**Issue by imorland** [flarum/framework#3663]
### Current Behavior

When running tests which involve the `Formatter`, the formatter cache is not cleared at the end of the test run

### Steps to Reproduce

- Run a test which does not enable `flarum/markdown`
- Write a test which enabled `flarum/markdown`
- test the output
- run both tests again, notice that the previous first test now fails

By adding
```php
protected function tearDown(): void
    {
        parent::tearDown();

        resolve(Formatter::class)->flush();
    }
```

To the test class, behaviour is as would be expected.

### Expected Behavior

The `Formatter` cache should be cleared as part of `tearDown()`

### Environment

- Flarum version: x.y.z
- Website URL: http://example.com
- Webserver: [e.g. apache, nginx]
- Hosting environment: [e.g. shared, vps]
- PHP version: x.y.z
- Browser: [e.g. chrome 67, safari 11]

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Comment by n-peugnet** [comment]
Similarly to this, the application's cache is not cleared between each tests, this took me quite some time to realize while trying to write some tests for code that interact with the cache.

I solved it by clearing the cache myself in the `tearDown()` using this line:

```php
$this->app()->getContainer()->make(\Illuminate\Contracts\Cache\Store::class)->flush();
```

But IMO this should be always done, as the tests should be as independent from each other as possible.

**Comment by SychO9** [comment]
PR welcome :)
