### ISSUE TITLE
Notifications on post approval broken

### ISSUE THREAD

**Issue by GreXXL** [flarum/framework#3687]
### Current Behavior

With the recent pull request (https://github.com/flarum/framework/pull/3656) it was fixed that a notification should be triggered when a post gets approved. This works perfectly when you are subscribed to a discussion. The notification "Someone replies to one of my posts" does not fire on approval, though.

The issue was reported here: https://discuss.flarum.org/d/31988-i-have-updated-16-how-can-i-set-the-web-notification/

### Steps to Reproduce

1. Create a discussion as user A
2. Create a reply as user B (that gets into the approval queue)
3. Approve the reply
4. No notification is fired for user A

Prerequisites:
- "Someone replies to one of my posts" enabled
- Discussion not followed by user A

### Expected Behavior

Notification for post reply fired and displayed

### Environment

- Flarum version: 1.6.2

**Comment by SychO9** [comment]
Technically, nothing is broken, it's just not currently a feature that mentions notifications are sent after approval, but that in itself can also be considered a bug. (A reply to a post is a post mention).

**Comment by GreXXL** [comment]
Well there is a separate notification setting for replies to a post. I understand that technically it's a post-mention. But there is separate notification for that as well. I think it's reasonable to think that the reply-notification should work when the reply gets approved.
