### ISSUE TITLE
The problem with the button name displayed by Nickname in the personal settings page

### ISSUE THREAD

**Issue by efast1568** [flarum/framework#3704]
### Current Behavior

On the settings page, the "Change Nickname" button is repeated. 

### Steps to Reproduce

User Settings Page

### Expected Behavior

 From the content, one of them should be "Request". It is recommended to distinguish them.

### Screenshots

[Imgur](https://imgur.com/zyPppwq)

### Environment

- Flarum version: 1.6.2
- Website URL: http://example.com
- Webserver: [e.g. apache, nginx]
- Hosting environment: [e.g. shared, vps]
- PHP version: x.y.z
- Browser: [e.g. chrome 67, safari 11]

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Comment by SychO9** [comment]
Can't reproduce, most likely an extension, can you try without any extensions that customize the settings page?

**Comment by efast1568** [comment]
oops, caused by "FoF Username Request", using the same button label

**Comment by SychO9** [comment]
Feel free to report that in the for user name request repository 👍🏼
