### ISSUE TITLE
Flarum Mentions performance issue

### ISSUE THREAD

**Issue by iPurpl3x** [flarum/framework#3705]
### Current Behavior

When `flarum/mentions` is enabled, the performance of showing a discussion with a lot of comments AND a lot of `post_mentions` is very bad. Seems like it loads a whole lot of relationships (posts and users), even though only 20 posts (pagination limit) should be loaded...

The SQL query that loads them (found in my local SQL logs is the following: 

```sql
select `posts`.*,
	`post_mentions_post`.`mentions_post_id` as `pivot_mentions_post_id`,
	`post_mentions_post`.`post_id` as `pivot_post_id`
from `posts`
	inner join `post_mentions_post` on `posts`.`id` = `post_mentions_post`.`post_id`
where `post_mentions_post`.`mentions_post_id` in (...)
	and `type` in (...);
```

I didn't really investigate what part of the code executes that query.

### Steps to Reproduce

In my test case, I looked at a discussion with 2k+ comments and around 400 post_mentions, many of them mentioning the first post (the fact that the mentions are on the first post might be the reason for this issue to happen). The API result is 400kb big and takes more than 2s to load, which is unacceptable.

### Expected Behavior

I think mentions should be paginated or limited in some way, so that such edge-cases remain scalable.

### Environment

- Flarum version: 1.6.2
- PHP version: 8

### Possible Solution

Limiting, paginating `post_mentions`.

**Comment by SychO9** [comment]
Noticed this in a large community a few weeks back. The solution for this should be the same as the solution for limiting retrieved post likes, as it's the same issue (here we're retrieving post `mentionedBy`).

**What needs to be done**
* Create a new relationship that only grabs 3 models. (for example `return $this->mentionedBy()->limit(3);`
* Change the serializer(s) to use that new relationship.
* Include somewhere in the code (can't tell right away) a retrieval for total model count (`->withCount('mentionedBy')` should be used) .
* Expose that count in the serializer.
* On the UI side, check if the count exceeds the limit. If the total exceeds the limit, allow opening a modal that lists all models (again, this logic to me should be applicable to the likes performance issue as well).
* We'll probably need to add some filtering to the existing endpoints to be able to retrieve all relevant models for the modal (paginated).
* The limit number should probably be a constant somewhere and exposed to the front end as well.

**Comment by iPurpl3x** [comment]
See it in action here : https://bookcircle.orellfuessli.ch/d/16533-wir-feiern-2-jahre-book-circle

Thanks @SychO9 for the insights!

**Comment by SychO9** [comment]
A relevant package so we can eager load a limit on the many relationships using SQL window functions: https://github.com/staudenmeir/eloquent-eager-limit

**Comment by luceos** [comment]
Root of the issue is that another mentions feature was merged without our tests measuring the consequences on performance. Imo we should look into one "simple" test that runs the rendering of one large discussion and measure the speed. We can then display the delta inside PR's next to other information. Understanding the delta, even as a fraction of change, will allow us to better understand the implications to rendering time.
