### ISSUE TITLE
flarum-tags does not export any JS functions to use in extensions

### ISSUE THREAD

**Issue by n-peugnet** [flarum/framework#3707]
### Current Behavior

The [documentation about importing from extensions](https://docs.flarum.org/extend/extending-extensions#webpackconfigjs) explains how to import from `flarum-tags` extension. So I was hoping to be able to use the `tagLabel` function this way. But it turns out nothing is exported by this extension. Which is unfortunate when trying to follow the exemple.

This issue has already been [reported on the forum](https://discuss.flarum.org/d/19903-how-does-useextensions-work) but has not received any answer.

### Steps to Reproduce

1. Follow this documentation page : https://docs.flarum.org/extend/extending-extensions
2. Expect to be able to use some functions from the demonstrated `flarum-tags` extension
3. Find out after many tries that nothing is actually exported by this extension

### Expected Behavior

The `flarum-tags` extension should export at least some of its functions. Not only to make fix the exemple in the docs but also to give more possibilities to extension developers.

As the tags extension is almost always installed, it may be interesting to extend its features. And giving access to function to allow displaying tags would be very useful.

### Environment

- Flarum version: 1.6.2
- Website URL: localhost
- Webserver: PHP Built-in web server
- Hosting environment: local machine
- PHP version: 8.1.12
- Browser: Mozilla Firefox 107.0.1

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

### Possible Solution

Add exports for at least `tagLabel`, `tagsLabel` and `tagIcon` to `flarum-tags` to make them accessible to extensions.

**Comment by davwheat** [comment]
Tags does export its JS, but not in the standard way used for 3rd party extensions.

The documentation needs to be changed to reflect this.

You can import this function like so:

```js
import tagLabel from 'flarum/tags/helpers/tagLabel';
```

**Comment by n-peugnet** [comment]
> You can import this function like so:
> 
> ```js
> import tagLabel from 'flarum/tags/helpers/tagLabel';
> ```

Thank you, this is working as expected! It seems the [Webpack step](https://docs.flarum.org/extend/extending-extensions#webpackconfigjs) is not needed with this method of import:

> ```jsonc
> module.exports = require('flarum-webpack-config')({
>     // Provide the extension IDs of all extensions from which your extension will be importing.
>     // Do this for both full and optional dependencies.
>     useExtensions: ['flarum-tags']
> });
> ```

**Comment by SychO9** [comment]
https://github.com/flarum/docs/issues/456
