### ISSUE TITLE
PHP Xdebug has detected a possible infinite loop when logged in with non-admin user

### ISSUE THREAD

**Issue by n-peugnet** [flarum/framework#3710]
### Current Behavior

When using [PHP Xdebug](https://xdebug.org/) for development purpose, logging-in or signing-up with a non-admin user (e.g. a newly created one) I get the following warning and xdebug stops the thread:

    [Thu Dec 15 13:11:09 2022] PHP Warning:  Uncaught Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '200' frames in /home/nicolas/Source/www/flarum/vendor/illuminate/collections/Traits/EnumeratesValues.php:981

Disabling Xdebug (e.g. with `sudo phpdismod xdebug`) allows the script to continue and eventually display the page.

I would like to be able to use Xdebug while developing Flarum extension.

It seems Xdebug is wrong with its assumption about a possible infinite loop, but it may however still be a performance problem to have such deep stack nesting. 

Here is the full log of the error: [xdebug_possible_infinite_loop_200_frames.log](https://github.com/flarum/framework/files/10237062/xdebug_possible_infinite_loop_200_frames.log)

### Steps to Reproduce

On a Debian based Linux distribution, assuming a working fresh install of Flarum (with mailer configured):

1. make sure `php-xdebug` installed and enabled
    
       sudo apt install php-xdebug
       sudo phpenmod xdebug

2. run server then visit `http://localhost:8080`

       php -S localhost:8080 -t public

3. sign up a new user
4. get the above PHP Xdebug error
5. disable Xdebug then restart server

       sudo phpdismod xdebug

6. refresh the page and now everything is working

### Expected Behavior

Being able to use Xdebug while developing Flarum extensions.

### Environment

- Flarum version: 1.6.2
- Website URL: http://localhost:8080
- Webserver: PHP Built-in web server
- Hosting environment: local machine
- PHP version: PHP 8.1.12 (cli)
- Browser: Mozilla Firefox 107.0.1

### Output of `php flarum info`

```
Flarum core 1.6.2
PHP version: 8.1.12
MySQL version: 10.6.10-MariaDB-1+b1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, intl, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, Zend OPcache, xdebug
+----------------------+---------+--------+
| Flarum Extensions    |         |        |
+----------------------+---------+--------+
| ID                   | Version | Commit |
+----------------------+---------+--------+
| flarum-flags         | v1.6.1  |        |
| flarum-approval      | v1.6.1  |        |
| flarum-tags          | v1.6.1  |        |
| flarum-suspend       | v1.6.1  |        |
| flarum-subscriptions | v1.6.1  |        |
| flarum-sticky        | v1.6.1  |        |
| flarum-statistics    | v1.6.1  |        |
| flarum-mentions      | v1.6.1  |        |
| flarum-markdown      | v1.6.1  |        |
| flarum-lock          | v1.6.1  |        |
| flarum-likes         | v1.6.1  |        |
| flarum-lang-english  | v1.6.0  |        |
| flarum-emoji         | v1.6.1  |        |
| flarum-bbcode        | v1.6.0  |        |
+----------------------+---------+--------+
Base URL: http://localhost:8080
Installation path: /home/nicolas/Source/www/flarum
Queue driver: sync
Session driver: file
Mail driver: smtp
Debug mode: ON

Don't forget to turn off debug mode! It should never be turned on in a production system.

```

**Comment by SychO9** [comment]
Can't reproduce, what are your tag restrictions like? it seems like the problem may at the tag access check level.

**Comment by n-peugnet** [comment]
> Can't reproduce, what are your tag restrictions like? it seems like the problem may at the tag access check level.

I had one restriction by tag, for testing purpose (just clicked once to add the tag without editing anything). I removed it but the issue persisted.

I just tried to set Flarum's own Debug mode to `false` and the issue did not happen. So I guess it only happens with both Xdebug and Flarum's debug mode enabled. This is still an issue, as when doing local development, it is not rare to enable both at the same time.

**Comment by n-peugnet** [comment]
Small update: this seems to happen only with Xdebug's default `develop` mode[^1][^2]. When I set the mode to `debug` using either of these methods the problem does not show up:

    XDEBUG_MODE=debug php -S localhost:8080 -t public
    php -d xdebug.mode=debug -S localhost:8080 -t public

[^1]: https://xdebug.org/docs/all_settings#mode
[^2]: https://xdebug.org/docs/develop

**Comment by luceos** [comment]
@n-peugnet how much is your nesting level for php configured at?

**Comment by n-peugnet** [comment]
> @n-peugnet how much is your nesting level for php configured at?

I guess you are talking about the [`xdebug.max_nesting_level` setting](https://xdebug.org/docs/all_settings#max_nesting_level). I didn't set it myself so I imagine 200 is the default value on Debian. I tried to increase it with no luck. It seems 200 is the max I can specify.

    php -dxdebug.max_nesting_level=500 -S localhost:8080 -t public

However, using lower values than 200 works, it indeed affects this behaviour by stopping the execution sooner. Maybe I should report this problem to Xdebug instead.

Anyways, this is not that much of a problem for me anymore as I mostly use the `debug` mode and not that much the `develop` one. Feel free to close this issue whenever you want.

**Comment by linc** [comment]
For what it's worth, I also ran into this with `xdebug.mode=develop` and switching to `debug` worked. PHP 8.1 on a forum I've been running import tests on and hadn't loaded in a few months, so who knows what triggered it. It was specifically being logged in already as a non-admin, I think.
