### ISSUE TITLE
Cannot be selected in browser Edge

### ISSUE THREAD

**Issue by niudehua** [flarum/framework#3728]
### Current Behavior

<img width="1590" alt="image" src="https://user-images.githubusercontent.com/36468944/217895384-8ea3fb89-956f-4e70-9383-af36ee6cffdd.png">

### Steps to Reproduce

https://docs.flarum.org/

### Expected Behavior

https://docs.flarum.org/

### Screenshots

<img width="1590" alt="image" src="https://user-images.githubusercontent.com/36468944/217895795-dda60ad7-0233-4031-ac36-2cdc1c66997a.png">

### Environment

- Website URL: https://docs.flarum.org/
- Browser: Microsoft Edge 109.0.1518.78  (arm64)

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Comment by luceos** [comment]
What cannot be selected? Another language? I'm on Version 109.0.1518.78 (Official build) (64-bit) and it works just fine.

Please provide more information, if done please reopen.
