### ISSUE TITLE
Fetch discussions from the API using `app.store.find()` with an array if ids just loads a page of 20 discussions

### ISSUE THREAD

**Issue by n-peugnet** [flarum/framework#3739]
### Current Behavior

Calling [`app.store.find` with an array if ids](https://api.docs.flarum.org/js/v1.6.0/classes/common_store.store#find.find-4) just loads a page of 20 discussions. The filter parameters are indeed sent from the client, but the API seems to ignore it completely.

### Steps to Reproduce

1. Go to a Flarum install with at least 20 discussions.
2. Open the browser's JS console.
3. Call `app.store.find()` with multiple ids, e.g. `app.store.find('discussions', [8, 9])`.
4. Find the corresponding request in the "Network" tab and see:
    1. That the request seems appropriate: `https://discuss.flarum.org/api/discussions?filter[id]=8,9`
    2. That the response contains instead of the 2 requested discussions, a full page of discussions, and not even the requested ones for sure.

Example response on `discuss.flarum.org`:

data | [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
-- | --
0 | Object { type: "discussions", id: "31967", attributes: {…}, … }
1 | Object { type: "discussions", id: "32042", attributes: {…}, … }
2 | Object { type: "discussions", id: "31999", attributes: {…}, … }
3 | Object { type: "discussions", id: "859", attributes: {…}, … }
4 | Object { type: "discussions", id: "4699", attributes: {…}, … }
5 | Object { type: "discussions", id: "23229", attributes: {…}, … }
6 | Object { type: "discussions", id: "30983", attributes: {…}, … }
7 | Object { type: "discussions", id: "23219", attributes: {…}, … }
8 | Object { type: "discussions", id: "32248", attributes: {…}, … }
9 | Object { type: "discussions", id: "27939", attributes: {…}, … }
10 | Object { type: "discussions", id: "32412", attributes: {…}, … }
11 | Object { type: "discussions", id: "5203", attributes: {…}, … }
12 | Object { type: "discussions", id: "28646", attributes: {…}, … }
13 | Object { type: "discussions", id: "4154", attributes: {…}, … }
14 | Object { type: "discussions", id: "31659", attributes: {…}, … }
15 | Object { type: "discussions", id: "32414", attributes: {…}, … }
16 | Object { type: "discussions", id: "32100", attributes: {…}, … }
17 | Object { type: "discussions", id: "22231", attributes: {…}, … }
18 | Object { type: "discussions", id: "32408", attributes: {…}, … }
19 | Object { type: "discussions", id: "32413", attributes: {…}, … }
included | [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
0 | Object { type: "users", id: "20612", attributes: {…} }
1 | Object { type: "users", id: "3190", attributes: {…} }
2 | Object { type: "users", id: "35559", attributes: {…} }
3 | Object { type: "users", id: "17578", attributes: {…} }
4 | Object { type: "users", id: "1", attributes: {…} }
5 | Object { type: "users", id: "1376", attributes: {…} }
6 | Object { type: "users", id: "4804", attributes: {…} }
7 | Object { type: "users", id: "30495", attributes: {…} }
8 | Object { type: "users", id: "40898", attributes: {…} }
9 | Object { type: "users", id: "33989", attributes: {…} }
10 | Object { type: "users", id: "30906", attributes: {…} }
11 | Object { type: "users", id: "37739", attributes: {…} }
12 | Object { type: "users", id: "40114", attributes: {…} }
13 | Object { type: "users", id: "40845", attributes: {…} }
14 | Object { type: "users", id: "5855", attributes: {…} }
15 | Object { type: "users", id: "35873", attributes: {…} }
16 | Object { type: "users", id: "28505", attributes: {…} }
17 | Object { type: "users", id: "8906", attributes: {…} }
18 | Object { type: "users", id: "39443", attributes: {…} }
19 | Object { type: "users", id: "40872", attributes: {…} }
20 | Object { type: "users", id: "40537", attributes: {…} }
21 | Object { type: "users", id: "40878", attributes: {…} }
22 | Object { type: "users", id: "40921", attributes: {…} }
23 | Object { type: "users", id: "40924", attributes: {…} }
24 | Object { type: "tags", id: "7", attributes: {…}, … }
25 | Object { type: "tags", id: "16", attributes: {…} }
26 | Object { type: "tags", id: "48", attributes: {…} }
27 | Object { type: "tags", id: "65", attributes: {…}, … }
28 | Object { type: "tags", id: "72", attributes: {…}, … }
29 | Object { type: "tags", id: "24", attributes: {…} }
30 | Object { type: "tags", id: "25", attributes: {…}, … }
31 | Object { type: "tags", id: "61", attributes: {…}, … }
32 | Object { type: "tags", id: "110", attributes: {…}, … }
33 | Object { type: "posts", id: "207844", attributes: {…} }
34 | Object { type: "posts", id: "208389", attributes: {…} }
35 | Object { type: "posts", id: "208034", attributes: {…} }
36 | Object { type: "posts", id: "7328", attributes: {…} }
37 | Object { type: "posts", id: "36516", attributes: {…} }
38 | Object { type: "posts", id: "124911", attributes: {…} }
39 | Object { type: "posts", id: "199662", attributes: {…} }
40 | Object { type: "posts", id: "124836", attributes: {…} }
41 | Object { type: "posts", id: "209958", attributes: {…} }
42 | Object { type: "posts", id: "171387", attributes: {…} }
43 | Object { type: "posts", id: "211137", attributes: {…} }
44 | Object { type: "posts", id: "40657", attributes: {…} }
45 | Object { type: "posts", id: "178501", attributes: {…} }
46 | Object { type: "posts", id: "33035", attributes: {…} }
47 | Object { type: "posts", id: "205439", attributes: {…} }
48 | Object { type: "posts", id: "211148", attributes: {…} }
49 | Object { type: "posts", id: "208933", attributes: {…} }
50 | Object { type: "posts", id: "115684", attributes: {…} }
51 | Object { type: "posts", id: "211104", attributes: {…} }
52 | Object { type: "posts", id: "211140", attributes: {…} }

### Expected Behavior

I expect that calling `app.store.find()` with an array of ids would fetch from the API only the requested ids. And that if one of the requested discussion is not in the response, then it is not accessible by the current user.

### Environment

- Flarum version: 1.6.3
- Website URL: https://forum.club1.fr (https://discuss.flarum.org, etc.)
- Webserver: non-relevant
- Hosting environment: non-relevant
- PHP version: 8.2.2, 7.4.3-4ubuntu2.17
- Browser: Mozilla Firefox 109.0

### Output of `php flarum info`

```
Flarum core 1.6.3
PHP version: 7.4.3-4ubuntu2.17
MySQL version: 5.5.5-10.5.19-MariaDB-1:10.5.19+maria~ubu2004
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, intl, json, ldap, exif, memcache, msgpack, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache
+-------------------------------+------------------+--------+
| Flarum Extensions             |                  |        |
+-------------------------------+------------------+--------+
| ID                            | Version          | Commit |
+-------------------------------+------------------+--------+
| flarum-tags                   | v1.6.1           |        |
| flarum-suspend                | v1.6.1           |        |
| flarum-markdown               | v1.6.1           |        |
| zerosonesfun-composer-preview | 1.1.9            |        |
| tituspijean-auth-ldap         | dev-modifs-club1 |        |
| the-turk-diff                 | 1.1.2            |        |
| nearata-remove-pane           | v2.0.1           |        |
| ianm-syndication              | 1.3.0            |        |
| fof-user-bio                  | 1.1.1            |        |
| fof-formatting                | 1.0.2            |        |
| fof-default-user-preferences  | 1.2.0            |        |
| flarum-subscriptions          | v1.6.3           |        |
| flarum-sticky                 | v1.6.1           |        |
| flarum-statistics             | v1.6.1           |        |
| flarum-mentions               | v1.6.3           |        |
| flarum-lock                   | v1.6.1           |        |
| flarum-likes                  | v1.6.1           |        |
| flarum-lang-french            | v4.5.0           |        |
| flarum-lang-english           | v1.6.0           |        |
| flarum-flags                  | v1.6.1           |        |
| datlechin-discussion-count    | v0.1.0           |        |
| club-1-cross-references       | dev-main         |        |
| askvortsov-checklist          | v1.3.1           |        |
+-------------------------------+------------------+--------+
Base URL: https://forum.club1.fr
Installation path: /var/www/forum.club1.fr
Queue driver: sync
Session driver: file
Mail driver: smtp
Debug mode: off
```

**Comment by n-peugnet** [comment]
Sorry I just found out after filling this issue that this has already been reported in #1694, but it was closed in 2018 as "this is simply not implemented". As this function call is in the JS API docs since `1.0.0` I do consider this a bug.

**Comment by SychO9** [comment]
Hello,

This is not a bug, it just is/was never a feature to filter discussions by ID. The API docs aren't wrong either because depending on the model you're trying to find, the ID filter might be implemented in the backend, and if so, it would give you the right results.

Feel free to PR this feature however, the post model ID filter can be used as an example: https://github.com/flarum/framework/blob/0da069ba9fe0ba2c742998f5fc7a7cc94eeb239e/framework/core/src/Post/Filter/IdFilter.php _- and if you do, don't forget an integration test ;) -_

Gonna close as we are only keeping track of bugs here and features on the forum.

**Comment by n-peugnet** [comment]
> Feel free to PR this feature however, the post model ID filter can be used as an example: https://github.com/flarum/framework/blob/0da069ba9fe0ba2c742998f5fc7a7cc94eeb239e/framework/core/src/Post/Filter/IdFilter.php _- and if you do, don't forget an integration test ;) -_

Thank you for the hint. I must admit that I searched how to add this filter but was kind of lost in all the different classes involved.

I will probably try to add this feature soon™.

**Comment by n-peugnet** [comment]
Maybe adding a comment in the JS API docs that warns about this filter being possibly not implemented depending on the Model could be more explicit? I suspect that other Models than Discussion's one are also affected by this issue.
