### ISSUE TITLE
Cannot delete user accounts

### ISSUE THREAD

**Issue by SychO9** [flarum/framework#3745]
### Current Behavior

Deleting a user account fails with a server error

### Steps to Reproduce

1. Delete user

### Expected Behavior

Shouldn't

### Environment

- Flarum version: x.y.z
- Website URL: http://example.com
- Webserver: [e.g. apache, nginx]
- Hosting environment: [e.g. shared, vps]
- PHP version: x.y.z
- Browser: [e.g. chrome 67, safari 11]

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

### Additional Context

Was introduced in #3587

**Comment by nonfreegithub** [comment]
same issue here
