### ISSUE TITLE
`isDark` throws an error and the app crashes if a color is set to `NULL` in the database

### ISSUE THREAD

**Issue by iPurpl3x** [flarum/framework#3764]
### Current Behavior

When a tag is saved in the database with the `color` column set to `NULL`, then when trying to display that tag in the UI, there will be an error as the `isDark` util will try to call `replace` on a `null` variable. The app crashes then because of this.

### Steps to Reproduce

1. Set the color column of a tag to `NULL`
2. Open that tag index page

### Expected Behavior

No error

### Environment

- Flarum version:1.7.1
- PHP version: 8.1

**Comment by SychO9** [comment]
this doesn't seem to trigger any errors on a normal flarum instance, since the color value when creating/editing is always a string on the database. Is that correct for your case?

**Comment by iPurpl3x** [comment]
That is correct, most entries in my db have an empty string as value, but some have `NULL`. I guess this has been changed manually or by an external script. But either the color column should not be nullable or this error needs to be fixed, for safety.

**Comment by davwheat** [comment]
I'd propose making it not nullable since that is what Flarum already expects.

**Comment by SychO9** [comment]
changing the column now would break any instances that have null values, so I think we need to make the util param nullable and check. Though since by default the color column is always a string from the vanilla app, this can probably just go into 1.8 rather than a patch.

**Comment by davwheat** [comment]
Why do we not just convert NULL values to empty strings and then make it not nullable?

**Comment by SychO9** [comment]
wouldn't it count as a breaking change though if a nullable column is made non-nullable? the case in this issue is that there is custom code that sets null values because it's possible.

**Comment by davwheat** [comment]
I suppose... my thought is that it shouldn't have null values and anyone doing that is doing it wrong, but realistically null values actually make more sense than empty strings.

**Comment by iPurpl3x** [comment]
I agree that 
> realistically null values actually make more sense than empty strings.

And of course, no need for a patch release, I can do a small db request to set all columns that are NULL to EMPTY.
