### ISSUE TITLE
Undoing Hiding (ignoring) discussions

### ISSUE THREAD

**Issue by garygreen** [flarum/framework#3770]
### Current Behavior

When ignoring a discussion it hides it from the main discussion listing - however there doesn't appear to be any way to undo and see the discussion again. From the perspective of the user the discussion essentially disappears forever.

![image](https://user-images.githubusercontent.com/1702638/226150957-95bd8ca7-37f6-4a73-af51-64ce36889ad2.png)

A fix could be to show the list of "Hidden" discussions on the user's settings/profile page, so they can show them again if needed, or have some kind of "Hidden" discussion filter. Or maybe it could be as simple as adding a "Hidden" sort option to the discussion list, so it shows the hidden discussions first:

![image](https://user-images.githubusercontent.com/1702638/226151145-89ce4fcd-d69c-4a9a-932a-a04bc26b8643.png)

### Steps to Reproduce

As above

### Expected Behavior

Should be able to undo the "Ignoring" discussion option

### Environment

- Flarum version: 1.7

**Comment by SychO9** [comment]
I don't see this as a bug, the feature works as described. This is more of a feature request to add a filter to show ignored discussions or to list ignored discussions somewhere.

**Comment by garygreen** [comment]
I wasn't sure whether to label it a bug or feature, because Ignoring/Hiding discussions is a core feature. So once users close the discussion they cannot ever see it again, unless they bookmarked it in their browser. I know that sounds potentially strange, but one of the use cases for "Ignoring" discussion is to hide discussions temporarily that are heated, or topical, yet still be able to come back to them later if they wish.

Please advise if you would be open to a PR to add the feature? How would you like it to be implemented?

**Comment by SychO9** [comment]
What would make most sense imho, is a filter, however we don't have a UI for filters, and won't be looking into one until 2.0

Other approaches like an additional tab listing hidden discussions sound like potential clutter 🤔 

Considering 2.0 development will start soon (see https://discuss.flarum.org/d/32539-staff-diary-v18-cycle) we should wait until we've implemented said filter UI.

**Comment by SychO9** [comment]
https://discuss.flarum.org/d/32660-see-ignored-discussions-and-undo
