### ISSUE TITLE
flarum/flags should use pagination

### ISSUE THREAD

**Issue by iamdarkle** [flarum/framework#3787]
### Current Behavior

Currently in one of the forums I manage I have about 450 flagged posts that are somewhat stagnant, the thing is that when you click on the dropdown it takes some time to display the list (even if I remember correctly after 150 you can start to notice a slowdown), I think it would be good to introduce pagination to avoid this, similar to the one used in the notifications dropdown.

### Steps to Reproduce

1. Flag several hundred posts
2. Open the flags dropdown

### Environment

- Flarum version: 1.7.2
- PHP version: 8.2.4

### Possible Solution

Make use pagination to improve performance and avoid lots of requests.

**Comment by SychO9** [comment]
relates to https://github.com/flarum/issue-archive/issues/53
