### ISSUE TITLE
[Package Manager] updating when using beta packages

### ISSUE THREAD

**Issue by SychO9** [flarum/framework#3792]
### Current Behavior

Production instances have `stable` minimum stability by default. Sometimes we need to be able to try beta packages, but the update command fails because minimum stability is `stable`.

### Steps to Reproduce

1. Install a beta package (packamanager itself is beta)
2. Run a global update

### Expected Behavior

We should be able to update without a hitch.

### Environment

- Flarum version: x.y.z
- Website URL: http://example.com
- Webserver: [e.g. apache, nginx]
- Hosting environment: [e.g. shared, vps]
- PHP version: x.y.z
- Browser: [e.g. chrome 67, safari 11]

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

### Possible Solution

Perhaps allow changing the minimum stability to beta from the UI, while using `--prefer-stable` in update commands.

**Comment by askvortsov1** [comment]
> Perhaps allow changing the minimum stability to beta from the UI, while using --prefer-stable in update commands.

Feels like this should be simple enough to do with a setting and a toggle switch
