### ISSUE TITLE
"Mentioned by" on posts sometimes leaks hidden posts

### ISSUE THREAD

**Issue by matteocontrini** [flarum/framework#3846]
### Current Behavior

When a post (A) is mentioned by another post (B), and post B is hidden, the "mentioned by" section at the bottom of post A shows the preview of post B, even if the post is hidden and the user/actor is not authorized to see hidden posts.

Note that this doesn't happen if https://github.com/flarum/issue-archive/issues/76 gets in the way: in that case, the mention is deleted from the db and thus post A doesn't show post B as a reply to it.

If you're wondering why this issue actually exists, since https://github.com/flarum/issue-archive/issues/76 should make it impossible: I have no idea, I just know for sure that it happens even on the latest stable version, after seeing multiple occurences of that on a forum I manage (see example below).

### Steps to Reproduce

Theoretically, these would be the steps that reproduce the issue:

1. Create post A
2. Create post B as a reply to post A
3. Delete post B
4. Logout or login as a non-privileged user and notice that on post A it says that post B is a reply, and you can see a preview of it

<img width="932" alt="image" src="https://github.com/flarum/framework/assets/2164763/ee79fe25-84ab-4304-8e08-075e0bf2e9b9">

The post by `Joanlui` in the screenshot above is actually hidden. (Ignore the gap between the two posts, that's a placeholder for ads.)

What I see as an admin:

<img width="908" alt="image" src="https://github.com/flarum/framework/assets/2164763/49f8598e-223e-4fad-8706-821f6f29449b">

Link to that post, if it helps: https://forum.fibra.click/d/25781-bolletta-luce-e-gas-cosa-scelgo/8274

### Expected Behavior

Hidden posts should never be shown to standard users.

### Environment

- Flarum version: 1.8.1

### Output of `php flarum info`

I can provide it if relevant.

**Comment by SychO9** [comment]
@matteocontrini could you provide `php flarum info` and your database version please?

**Comment by luceos** [comment]
I just tried replicating this:

https://discuss.flarum.org/d/33052-mentioned-by

<img width="680" alt="image" src="https://github.com/flarum/framework/assets/504687/03ba9e3f-bb7f-483a-80de-4ad4514bf4ac">

incognito:

<img width="595" alt="image" src="https://github.com/flarum/framework/assets/504687/b130e6c4-5f06-40a0-800f-d632717f67a6">

I can't replicate it, so might be an extension. Can you either: a) disable extensions one by one to see if this re-occurs or b) provide a composer.json so we can attempt to reproduce locally?

**Comment by imorland** [comment]
@matteocontrini if you upgrade to the latest `fof/merge-discussions` this problem should be resolved. Are you able to verify please? [This update was released as a recommended update last week](https://discuss.flarum.org/d/19460-friendsofflarum-merge-discussions/177)

**Comment by matteocontrini** [comment]
@imorland that was it, fixed, thank you everyone!

**Comment by imorland** [comment]
Excellent news @matteocontrini - thanks for confirming :)
