### ISSUE TITLE
Forum not working in IE11

### ISSUE THREAD

**Issue by SvenLie** [flarum/framework#3864]
### Current Behavior

The flarum demo doesn't work in internet explorer 11. First issue is that arrow functions are used in core.

### Steps to Reproduce

1. Go to https://demo.flarum.site/ in internet explorer 11

### Expected Behavior

Forum works in IE11

### Environment

- Flarum version: 1.8.x
- Website URL: https://demo.flarum.site/
- Browser: Internet Explorer 11

**Comment by SychO9** [comment]
Internet Explorer is not supported since it was retired. https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/
