### ISSUE TITLE
bug happens when replying again

### ISSUE THREAD

**Issue by PythonSmall-Q** [flarum/framework#3873]
### Current Behavior

when issueing a reply, it is normal. then, i posted another comment with the same account, it shows "The requested resource was not found."

### Steps to Reproduce

1. go to a discussion
2. post a reply
3. post another reply
4. shows "The requested resource was not found."

### Expected Behavior

the reply should be posted in another seperate comment

### Screenshots

![image](https://github.com/flarum/framework/assets/106425289/990e03f1-3b40-4e5c-80fe-1a7db3ef802e)

### Environment

- Flarum version: newest
- Website URL: http://xmoj.flarum.cloud
- Webserver: nginx
- Hosting environment: vps
- PHP version: 6.1.0
- Browser: Chrome 160

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Comment by luceos** [comment]
I cannot reproduce this on https://demo.flarum.site. Can you?

If you cannot reproduce it using your given instructions, then it is likely an issue with FreeFlarum. Please confirm this.
