### ISSUE TITLE
typo in js part of sticky plugin

### ISSUE THREAD

**Issue by TsXor** [flarum/framework#3886]
### Current Behavior

https://github.com/flarum/sticky/blob/main/js/src/forum/addStickyExcerpt.js#L9

### Steps to Reproduce

open that link

### Expected Behavior

that function name should be `addStickyExcerpt`

### Environment

LNMP

### Possible Solution

rename it

### Additional Context

This have't caused problems, but idk why.

**Comment by TsXor** [comment]
also, in code of sticky plugin, "sticky" can mean "a state of being sticky" or "make sticky", which may add some ambiguity

**Comment by TsXor** [comment]
- It seems that adding `is:sticky` to search query can search only "stickied" posts.
- HTML elements of sticky discussions can be identified with class `DiscussionListItem--sticky`.
Well, I failed to find where they are documented ...

**Comment by TsXor** [comment]
https://discuss.flarum.org/d/33369-weird-js-issue-relating-to-extensions-typeerror-t-is-undefined/2 seems to be related to this.
Look at the error:
![](https://cdn.discordapp.com/attachments/1066509176857174126/1153380767091671121/Screenshot_20230918_142250.png)
we can see in the exception stack: `loadPage DiscussionListState.ts:43`
and when we take a look at `addEssentialExcerpt.js`, we will find that **only** this file in `Sticky` plugin imported from `DiscussionListState.ts`

Also, the function `addEssentialExcerpt` makes pinned discussions show a 175-char abstract, which means that its missing can stop the page from loading.

Well, all the above things seems to make sense until I tried a compilation. `forum.js` didn't even change, which means that the typo is harmless.

**Comment by SychO9** [comment]
the typo is harmless, whatever error is caused in that report, it is most likely due to an extension.

**Comment by clarkwinkelmann** [comment]
If there was really a problem with the naming of the import, the entire extension would fail to compile before it's ever released publicly.

Most imports in Flarum javascript simply take the `default` export and give it a name that matches the file so the actual function name in the export rarely matters.

Still something we might want to rename internally, I assume it's a leftover from an older rename.

**Comment by SychO9** [comment]
the function was renamed in 2.0 but other then that, nothing to fix here.
