### ISSUE TITLE
Code blocks are hard to read in dark mode

### ISSUE THREAD

**Issue by TraceyC77** [flarum/framework#3896]
### Current Behavior

When reading a post on Flarum in dark mode, code blocks are difficult to read.

### Steps to Reproduce

Go to https://discuss.getsol.us/d/9761-firefox-glib-gobject-critical-errors-clutter-log
Switch to dark mode.

### Expected Behavior

Dark mode uses an appropriate style to make text readable in code blocks.

### Screenshots

![flarum_code_block_dark_mode](https://github.com/flarum/framework/assets/10402612/7a64d72b-30eb-4e5b-9c32-3391a90e41ad)

### Environment

- Website URL: https://discuss.getsol.us/
- Browser: Problem seen with Firefox 118.0.1, Vivaldi-stable 6.2.3105.54

I don't have access to the Flarum server instance to answer the rest of the questions. Given that this is a theming issue, it seems unnecessary anyway.

### Output of `php flarum info`

N/A

### Additional Context

I found this reported on the Flarum forums here:
https://discuss.flarum.org/d/30696-code-blocks-have-hard-to-read-colors-in-dark-mode

From the response, it sounded like it would be possible for Flarum to pass a different theme for dark mode vs. light mode. I searched this tracker but didn't see that an issue was ever opened for it.

Workarounds:
- View the post in light mode
- Use the nuTensor addon (or a similar addon) to block javascript from jsdelivr.net
This is what the post looks like with that js blocked:

![flarum_code_block_vivaldi](https://github.com/flarum/framework/assets/10402612/304a0ee2-1889-4a6f-9822-f58667778a94)

**Comment by Spencer-Robertson-ANU** [comment]
Hi there, I'd like to fix this, can I please be assigned? Thankyou

**Comment by shivesh96** [comment]
## Add Below code

> <style>
> #app pre > code span.hljs-string{
>     color: grey;
> }
> </style>

**Comment by luceos** [comment]
Dark mode is part of an extension and overriding the code blocks for that mode, as such, is the responsibility of the extension as well.
