### ISSUE TITLE
Content max limit is incorrect

### ISSUE THREAD

**Issue by vimar** [flarum/framework#3942]
### Current Behavior

When trying to write a very long post, I have received the following message:
> The content must not be greater than **65535** characters.

### Steps to Reproduce

1. Go to new discussion
2. Write a very long text (more than 65535 characters)
3. The message should appear

### Expected Behavior

As content field is a MySQL mediumtext type, it should be able to handle more than 65535 characters (Mediumtext size is equal to 2^24 size)

### Environment

- Flarum version: 1.8.0
- Website URL: https://forum.legendra.com/
- Webserver: apache
- PHP version: 8.2.x

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Comment by davwheat** [comment]
Post content is encoded into an XML-like format using [s9e/TextFormatter](https://github.com/s9e/TextFormatter).

What you type on the front-end is not identical to what gets stored in the database.

As a result, we have opted to artificially limit the content length that can be submitted versus what the database can handle.

There's no way we can easily inform users about the limits (as 1 character from the user could cause 10 characters from TextFormatter), hence the artificial limit is a better solution.

**Comment by luceos** [comment]
Although @davwheat is correct. One could use the validation extender to increase the content limit for specific purposes, though your database needs to support this as well.

So even if there is a default limit, there is a way to override that with a extender.

Closing for this and the above reason.
